@baseUrl = http://localhost:5000
@urlPath = api/v1


//contiene las solicitudes de registro de usuario
###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "Usuario",
  "password": "12345",
  "email": "usuario@gmail.com",
  "avatarColor": "green"
}

//contiene las solicitudes de inicio de session
###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "Usuario",
  "password": "12345"
}


//contiene las solicitudes obtener informacion del usuario actual
###
GET {{baseUrl}}/{{urlPath}}/currentUser
Content-Type: application/json
Accept: application/json
withCredentials: true

//contiene las solicitudes de cierre de sesión
###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

