@baseUrl = http://localhost:5000
@urlPath = api/v1


//contiene las solicitudes de registro de usuario
###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "gabriel",
  "password": "gabdev",
  "email": "gabriel.recabarren@gmail.com",
  "avatarColor": "black"
}

//contiene las solicitudes de inicio de session
###
POST {{baseUrl}}/{{urlPath}}/signin
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "username": "gabriel",
  "password": "gabdev"
}


//contiene las solicitudes obtener informacion del usuario actual
###
GET {{baseUrl}}/{{urlPath}}/currentUser
Content-Type: application/json
Accept: application/json
withCredentials: true

//contiene las solicitudes de cierre de sesión
###
GET {{baseUrl}}/{{urlPath}}/signout
Content-Type: application/json
Accept: application/json
withCredentials: true

//Solicitud de creacion de task
###
POST {{baseUrl}}/{{urlPath}}/createTask
Content-Type: application/json
Accept: application/json
withCredentials: true
{
    "title":"Tarea1",
    "description":"Descripcion 1",
    "dueDate":"2023-05-18T14:0",
    "completed": false

}
