//Solicitud de creacion de task
@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/createTask
Content-Type: application/json
Accept: application/json,
withCredentials: true
{

  "title": "Tarea1",
  "description": "Descripción 1",
  "completed": false
}

###
GET {{baseUrl}}/{{urlPath}}/getTask/:title
Content-Type: application/json
Accept: application/json
withCredentials: true

###
DELETE {{baseUrl}}/{{urlPath}}/deleteTask/:title
Content-Type: application/json
Accept: application/json
withCredentials: true

###
UPDATE {{baseUrl}}/{{urlPath}}/deleteTask/:title
Content-Type: application/json
Accept: application/json
withCredentials: true
